name: eds_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc: ^8.1.2
  carousel_slider: ^4.0.0
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4
  meta: ^1.9.1

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.4.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
